services:
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    ports:
      - "127.0.0.1:8123:8123" # HTTP interface
      - "127.0.0.1:9000:9000" # Native interface
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    environment:
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}
      - CLICKHOUSE_USER=${CLICKHOUSE_USER:-default}
    volumes:
      - ./ch_data:/var/lib/clickhouse
